# Generated by Django 3.0.5 on 2021-10-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidDomRu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Адрес')),
                ('house', models.CharField(max_length=50, verbose_name='Дом')),
                ('apartment', models.CharField(max_length=50, verbose_name='Кв.')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('service_tv', models.PositiveSmallIntegerField(choices=[(0, 'Нет'), (1, 'Да')], default=0, verbose_name='TV')),
                ('service_net', models.PositiveSmallIntegerField(choices=[(0, 'Нет'), (1, 'Да')], default=0, verbose_name='NET')),
                ('service_phone', models.PositiveSmallIntegerField(choices=[(0, 'Нет'), (1, 'Да')], default=0, verbose_name='PHONE')),
                ('comment', models.TextField(blank=True, verbose_name='Коментарий')),
                ('status', models.IntegerField(choices=[(0, 'Заявка поступила'), (1, 'Бот забрал заявку'), (2, 'Ошибка в заявке, передано оператору'), (3, 'Заявка отклонена, передано оператору'), (4, 'Заявка принята ДомРу.')], verbose_name='Статус')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
    ]
