# Generated by Django 3.0.5 on 2021-10-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidBeeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_login', models.CharField(max_length=200, verbose_name='Логин')),
                ('partner_workercode', models.CharField(max_length=200, verbose_name='Партнер')),
                ('partner_password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Адрес')),
                ('house', models.CharField(max_length=50, verbose_name='Дом')),
                ('apartment', models.CharField(max_length=50, verbose_name='Кв.')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('tarif', models.CharField(max_length=100, verbose_name='Тариф')),
                ('ctn_abonent', models.CharField(max_length=100, verbose_name='CTN абонента')),
                ('bid_number', models.CharField(max_length=100, verbose_name='Номер заявки')),
                ('status', models.IntegerField(choices=[(0, 'Заявка поступила'), (1, 'Бот забрал заявку'), (2, 'Ошибка в заявке, передано оператору'), (3, 'Заявка отклонена, передано оператору'), (4, 'Заявка принята Билайн')], verbose_name='Статус')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
        migrations.AlterField(
            model_name='biddomru',
            name='status',
            field=models.IntegerField(choices=[(0, 'Заявка поступила'), (1, 'Бот забрал заявку'), (2, 'Ошибка в заявке, передано оператору'), (3, 'Заявка отклонена, передано оператору'), (4, 'Заявка принята ДомРу')], verbose_name='Статус'),
        ),
    ]
