# Generated by Django 3.0.5 on 2021-10-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bidbeeline_id_lid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidbeeline',
            name='bot_log',
            field=models.TextField(blank=True, verbose_name='Лог бота'),
        ),
        migrations.AlterField(
            model_name='bidbeeline',
            name='bid_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='bidbeeline',
            name='ctn_abonent',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTN абонента'),
        ),
        migrations.AlterField(
            model_name='bidbeeline',
            name='status',
            field=models.IntegerField(choices=[(0, 'Заявка поступила'), (1, 'Бот забрал заявку'), (2, 'Ошибка отправки заявки, передано оператору'), (3, 'Заявка принята Билайн')], verbose_name='Статус'),
        ),
    ]
