# Generated by Django 3.0.5 on 2021-10-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bidmts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidmts',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='bidmts',
            name='locality',
            field=models.CharField(blank=True, max_length=200, verbose_name='Нас.пункт'),
        ),
        migrations.AlterField(
            model_name='bidmts',
            name='raion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Район'),
        ),
    ]
