# Generated by Django 3.0.5 on 2021-10-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211019_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidBeeline2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parther_key', models.CharField(max_length=200, verbose_name='Логин')),
                ('client_inn', models.CharField(max_length=200, verbose_name='Партнер')),
                ('client_name', models.CharField(max_length=200, verbose_name='Пароль')),
                ('id_lid', models.CharField(max_length=50, verbose_name='ID лида')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Город')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Кв.')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('products', models.CharField(max_length=100, verbose_name='Тариф')),
                ('bid_number', models.CharField(blank=True, max_length=100, verbose_name='Номер заявки')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Заявка поступила'), (1, 'Бот забрал заявку'), (2, 'Ошибка отправки заявки, передано оператору'), (3, 'Заявка принята Билайн')], verbose_name='Статус')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('bot_log', models.TextField(blank=True, verbose_name='Лог бота')),
            ],
        ),
        migrations.AlterField(
            model_name='bidbeeline',
            name='type_abonent',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Пакетные предложения'), (1, 'Абонент Билайн'), (2, 'Доставка СИМ'), (3, 'Доставка СИМ(MNP)')], verbose_name='Тип абонента'),
        ),
    ]
