# Generated by Django 3.0.5 on 2021-10-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211021_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidRostelecom2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, verbose_name='Логин')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('id_lid', models.CharField(max_length=50, verbose_name='ID лида')),
                ('firstname', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(default='', max_length=100, verbose_name='Отчество')),
                ('lastname', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('inn_organisation', models.CharField(max_length=100, verbose_name='ИНН/Организация')),
                ('service', models.CharField(max_length=100, verbose_name='Услуга')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('bid_number', models.CharField(blank=True, max_length=100, verbose_name='Номер заявки')),
                ('status', models.IntegerField(choices=[(0, 'Заявка поступила'), (1, 'Бот забрал заявку'), (2, 'Ошибка отправки заявки, передано оператору'), (3, 'Заявка принята Ростелеком')], verbose_name='Статус')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('bot_log', models.TextField(blank=True, verbose_name='Лог бота')),
            ],
        ),
    ]
