# Generated by Django 3.0.5 on 2021-11-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_bidrostelecom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidrostelecom',
            old_name='apatment',
            new_name='apartment',
        ),
        migrations.AlterField(
            model_name='bidrostelecom',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom',
            name='general_package',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Пакетное предл.'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom',
            name='service_home_internet',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Дом.интернет'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom',
            name='service_home_phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Дом.телефон'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom',
            name='service_interactive_tv',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Интерактивное ТВ'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom',
            name='service_iptv_packets',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Пакет каналов iTV'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom',
            name='service_mobile_connection',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Моб.связь'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom',
            name='service_smart_house',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Умный дом'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom',
            name='service_smart_intercom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Умный домофон'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom',
            name='service_wink_tv_online',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Wink-ТВ-онлайн'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom2',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom2',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom2',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество'),
        ),
    ]
