# Generated by Django 3.0.5 on 2021-11-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_bidttk'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidbeeline',
            name='dt_grafic',
            field=models.CharField(blank=True, max_length=100, verbose_name='В график'),
        ),
        migrations.AddField(
            model_name='bidbeeline',
            name='grafic_dop_info',
            field=models.TextField(blank=True, verbose_name='График Доп инфо'),
        ),
        migrations.AddField(
            model_name='bidbeeline',
            name='grafic_error',
            field=models.TextField(blank=True, verbose_name='Ошибки графика'),
        ),
    ]
