# Generated by Django 3.0.5 on 2021-11-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20211130_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidbeeline',
            name='region',
        ),
    ]
