# Generated by Django 3.0.5 on 2021-12-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_bidbeeline_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='TxvBeeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_login', models.CharField(max_length=200, verbose_name='Логин')),
                ('partner_workercode', models.CharField(max_length=200, verbose_name='Партнер')),
                ('partner_password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Адрес')),
                ('house', models.CharField(max_length=50, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=50, verbose_name='Кв.')),
                ('date_connect', models.CharField(blank=True, max_length=100, verbose_name='В график')),
                ('info_restrictions', models.TextField(blank=True, verbose_name='Ограничения')),
                ('tarifs_all', models.TextField(blank=True, verbose_name='Тарифы')),
                ('contract', models.CharField(blank=True, max_length=100, verbose_name='Договор')),
                ('find_date', models.CharField(blank=True, max_length=100, verbose_name='Найдена ли дата')),
                ('available_first_date_connect', models.CharField(blank=True, max_length=100, verbose_name='Доступная дата')),
                ('available_timeslot', models.CharField(blank=True, max_length=250, verbose_name='Таймслоты')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Запрос поступил'), (1, 'Бот забрал запрос'), (2, 'Ошибка обработки запроса'), (3, 'Запрос отработан')], verbose_name='Статус')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('bot_log', models.TextField(blank=True, verbose_name='Лог бота')),
            ],
        ),
    ]
