# Generated by Django 3.0.5 on 2021-12-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20211208_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txvdomru',
            name='available_connect',
            field=models.TextField(blank=True, verbose_name='ТхВ'),
        ),
        migrations.AlterField(
            model_name='txvdomru',
            name='pv_address',
            field=models.TextField(blank=True, verbose_name='ПВ адрес'),
        ),
    ]
