# Generated by Django 3.0.5 on 2021-12-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_txv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TxvBeeline',
        ),
        migrations.DeleteModel(
            name='TxvDomRu',
        ),
        migrations.DeleteModel(
            name='TxvMts',
        ),
        migrations.DeleteModel(
            name='TxvRostelecom',
        ),
        migrations.AlterModelOptions(
            name='txv',
            options={'verbose_name': 'ТхВ', 'verbose_name_plural': 'ТхВ'},
        ),
        migrations.AlterField(
            model_name='txv',
            name='region',
            field=models.CharField(blank=True, max_length=200, verbose_name='Область'),
        ),
    ]
