# Generated by Django 3.0.5 on 2021-12-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20211213_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidOnlime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, verbose_name='Логин')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('id_lid', models.CharField(max_length=50, verbose_name='ID лида')),
                ('firstname', models.CharField(blank=True, default='', max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
                ('apartment', models.CharField(max_length=10, verbose_name='Квартира')),
                ('entrances', models.CharField(max_length=10, verbose_name='Подъезд')),
                ('floor', models.CharField(max_length=10, verbose_name='Этаж')),
                ('tarifs_eq', models.CharField(blank=True, default='', max_length=250, verbose_name='Тариф, оборуд.')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('bid_number', models.CharField(blank=True, max_length=100, verbose_name='Номер заявки')),
                ('status', models.IntegerField(choices=[(0, 'Заявка поступила'), (1, 'Бот забрал заявку'), (2, 'Ошибка отправки заявки, передано оператору'), (3, 'Заявка принята Онлайм')], verbose_name='Статус')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('bot_log', models.TextField(blank=True, verbose_name='Лог бота')),
            ],
        ),
        migrations.AlterField(
            model_name='biddomru',
            name='apartment',
            field=models.CharField(max_length=10, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='bidrostelecom',
            name='apartment',
            field=models.CharField(max_length=10, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='bidttk',
            name='apartment',
            field=models.CharField(max_length=10, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='txv',
            name='pv_code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Билайн'), (2, 'ДомРу'), (3, 'МТС'), (4, 'Ростелеком'), (5, 'ТТК'), (6, 'ОнЛайм')], verbose_name='Оператор'),
        ),
    ]
