# Generated by Django 3.0.5 on 2021-12-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20211223_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='txv',
            name='login_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Логин_2'),
        ),
        migrations.AddField(
            model_name='txv',
            name='password_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Пароль_2'),
        ),
        migrations.AlterField(
            model_name='txv',
            name='pv_code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Билайн'), (2, 'ДомРу'), (3, 'МТС'), (4, 'Ростелеком'), (5, 'ТТК'), (6, 'ОнЛайм'), (7, 'МГТС')], verbose_name='Оператор'),
        ),
    ]
