# Generated by Django 3.0.5 on 2022-01-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20220114_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidmgts',
            name='count_tv',
            field=models.CharField(default='0', max_length=50, verbose_name='Кол-во ТВ'),
        ),
        migrations.AlterField(
            model_name='bidmgts',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bidmgts',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='bidmgts',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='bidmgts',
            name='tv_adapter',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ТВ приставка'),
        ),
        migrations.AlterField(
            model_name='bidmgts',
            name='wifi_router',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='wifi Роутер'),
        ),
    ]
