# Generated by Django 3.0.5 on 2022-01-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20220119_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidbeeline',
            name='street',
            field=models.CharField(max_length=200, verbose_name='Улица'),
        ),
    ]
