# Generated by Django 3.0.5 on 2021-12-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenumber',
            name='ats_except',
            field=models.BooleanField(default=False, verbose_name='Исключение для АТС'),
        ),
        migrations.AddField(
            model_name='mobilenumber',
            name='ats_except_min',
            field=models.IntegerField(default=0, verbose_name='Искл. АТС мин'),
        ),
    ]
