# Generated by Django 3.0.5 on 2021-12-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20211209_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenumber',
            name='ats_except_min',
            field=models.IntegerField(default=0, verbose_name='Искл АТС мин'),
        ),
    ]
