# Generated by Django 3.0.5 on 2021-10-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211013_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidbeeline',
            name='id_lid',
            field=models.CharField(default='222', max_length=50, verbose_name='ID лида'),
            preserve_default=False,
        ),
    ]
