# Generated by Django 3.0.5 on 2021-10-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211014_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidMTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, verbose_name='Логин')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('id_lid', models.CharField(max_length=50, verbose_name='ID лида')),
                ('region', models.CharField(max_length=200, verbose_name='Область')),
                ('raion', models.CharField(max_length=200, verbose_name='Район')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('locality', models.CharField(max_length=200, verbose_name='Нас.пункт')),
                ('street', models.CharField(max_length=200, verbose_name='Адрес')),
                ('house', models.CharField(max_length=50, verbose_name='Дом')),
                ('apartment', models.CharField(max_length=50, verbose_name='Кв.')),
                ('tarif', models.CharField(max_length=100, verbose_name='Тариф')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('bid_number', models.CharField(blank=True, max_length=100, verbose_name='Номер заявки')),
                ('status', models.IntegerField(choices=[(0, 'Заявка поступила'), (1, 'Бот забрал заявку'), (2, 'Ошибка отправки заявки, передано оператору'), (3, 'Заявка принята МТС')], verbose_name='Статус')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('bot_log', models.TextField(blank=True, verbose_name='Лог бота')),
            ],
        ),
    ]
