# Generated by Django 3.0.5 on 2021-10-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211020_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidbeeline2',
            name='client_inn',
            field=models.CharField(max_length=200, verbose_name='ИНН партнера'),
        ),
        migrations.AlterField(
            model_name='bidbeeline2',
            name='client_name',
            field=models.CharField(max_length=200, verbose_name='Название партнера'),
        ),
        migrations.AlterField(
            model_name='bidbeeline2',
            name='contact_name',
            field=models.CharField(max_length=200, verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='bidbeeline2',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='bidbeeline2',
            name='parther_key',
            field=models.CharField(max_length=200, verbose_name='Ключ партнера'),
        ),
        migrations.AlterField(
            model_name='bidbeeline2',
            name='products',
            field=models.CharField(max_length=200, verbose_name='Услуга'),
        ),
    ]
