# Generated by Django 3.0.5 on 2021-11-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_bidrostelecom2'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidRostelecom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, verbose_name='Логин')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('id_lid', models.CharField(max_length=50, verbose_name='ID лида')),
                ('firstname', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(default='', max_length=100, verbose_name='Отчество')),
                ('lastname', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
                ('apatment', models.CharField(max_length=10, verbose_name='Крвартира')),
                ('general_package', models.CharField(default='', max_length=100, verbose_name='Пакетное предл.')),
                ('service_home_internet', models.CharField(default='', max_length=100, verbose_name='Дом.интернет')),
                ('service_smart_house', models.CharField(default='', max_length=100, verbose_name='Умный дом')),
                ('service_smart_intercom', models.CharField(default='', max_length=100, verbose_name='Умный домофон')),
                ('service_interactive_tv', models.CharField(default='', max_length=100, verbose_name='Интерактивное ТВ')),
                ('service_wink_tv_online', models.CharField(default='', max_length=100, verbose_name='Wink-ТВ-онлайн')),
                ('service_home_phone', models.CharField(default='', max_length=100, verbose_name='Дом.телефон')),
                ('service_mobile_connection', models.CharField(default='', max_length=100, verbose_name='Моб.связь')),
                ('service_iptv_packets', models.CharField(default='', max_length=100, verbose_name='Пакет каналов iTV')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('bid_number', models.CharField(blank=True, max_length=100, verbose_name='Номер заявки')),
                ('status', models.IntegerField(choices=[(0, 'Заявка поступила'), (1, 'Бот забрал заявку'), (2, 'Ошибка отправки заявки, передано оператору'), (3, 'Заявка принята Ростелеком')], verbose_name='Статус')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('bot_log', models.TextField(blank=True, verbose_name='Лог бота')),
            ],
        ),
    ]
