# Generated by Django 3.0.5 on 2021-11-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211109_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidmts',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='bidmts',
            name='raion',
        ),
        migrations.AddField(
            model_name='bidmts',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='bidmts',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество'),
        ),
    ]
