# Generated by Django 3.0.5 on 2021-11-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211116_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BidDomRu',
            new_name='BidDomRu2',
        ),
    ]
