# Generated by Django 3.0.5 on 2021-11-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_biddomru'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidTtk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, verbose_name='Логин')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('id_lid', models.CharField(max_length=50, verbose_name='ID лида')),
                ('firstname', models.CharField(blank=True, default='', max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество')),
                ('lastname', models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
                ('apartment', models.CharField(max_length=10, verbose_name='Крвартира')),
                ('general_package', models.CharField(blank=True, default='', max_length=100, verbose_name='Общий пакет')),
                ('service_internet', models.CharField(blank=True, default='', max_length=100, verbose_name='Тариф интернет')),
                ('service_tv', models.CharField(blank=True, default='', max_length=100, verbose_name='Тариф ТВ')),
                ('equipment', models.CharField(blank=True, default='', max_length=1024, verbose_name='Оборудование')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('bid_number', models.CharField(blank=True, max_length=100, verbose_name='Номер заявки')),
                ('status', models.IntegerField(choices=[(0, 'Заявка поступила'), (1, 'Бот забрал заявку'), (2, 'Ошибка отправки заявки, передано оператору'), (3, 'Заявка принята ТТК')], verbose_name='Статус')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('bot_log', models.TextField(blank=True, verbose_name='Лог бота')),
            ],
        ),
    ]
