# Generated by Django 4.0.1 on 2022-01-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('val_str', models.CharField(blank=True, max_length=100, null=True)),
                ('val_bool', models.BooleanField(blank=True, null=True)),
                ('val_int', models.IntegerField(blank=True, null=True)),
                ('val_datetime', models.DateTimeField(blank=True, null=True)),
                ('val_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='MoexBOND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secid', models.CharField(max_length=100, unique=True, verbose_name='Тикер')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('matdate', models.DateTimeField(blank=True, null=True, verbose_name='Погашение')),
                ('facevalue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Номинал')),
                ('couponfrequency', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Куп./год')),
                ('couponvalue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Купон')),
                ('typename', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип')),
            ],
        ),
    ]
