# Generated by Django 4.0.1 on 2022-01-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalvariable',
            name='descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='globalvariable',
            name='val_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariable',
            name='val_bool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariable',
            name='val_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariable',
            name='val_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moexbond',
            name='couponfrequency',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Куп./год'),
        ),
        migrations.AlterField(
            model_name='moexbond',
            name='couponvalue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Купон'),
        ),
        migrations.AlterField(
            model_name='moexbond',
            name='facevalue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Номинал'),
        ),
        migrations.AlterField(
            model_name='moexbond',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='moexbond',
            name='secid',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тикер'),
        ),
        migrations.AlterField(
            model_name='moexbond',
            name='typename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип'),
        ),
    ]
