# Generated by Django 4.0.1 on 2022-01-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_typebond_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterbond',
            name='check_facevalue_from',
            field=models.BooleanField(blank=True, default='False', verbose_name='активно Номинал от'),
        ),
        migrations.AlterField(
            model_name='filterbond',
            name='check_facevalue_to',
            field=models.BooleanField(blank=True, default='False', verbose_name='активно Номинал до'),
        ),
        migrations.AlterField(
            model_name='filterbond',
            name='check_matdate_from',
            field=models.BooleanField(blank=True, default='False', verbose_name='активно Погашение от'),
        ),
        migrations.AlterField(
            model_name='filterbond',
            name='check_matdate_to',
            field=models.BooleanField(blank=True, default='False', verbose_name='активно Погашение до'),
        ),
        migrations.AlterField(
            model_name='filterbond',
            name='check_profit_from',
            field=models.BooleanField(blank=True, default='False', verbose_name='активно Доходность от'),
        ),
        migrations.AlterField(
            model_name='filterbond',
            name='check_profit_to',
            field=models.BooleanField(blank=True, default='False', verbose_name='активно Доходность до'),
        ),
    ]
