# Generated by Django 4.0.1 on 2022-01-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_alter_filterbond_check_facevalue_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moexbond',
            name='matdate',
            field=models.DateField(blank=True, null=True, verbose_name='Погашение'),
        ),
    ]
