# Generated by Django 3.0.5 on 2021-10-08 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GermanGroupPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Дайте короткое название группе', max_length=200, unique=True, verbose_name='Название группы')),
                ('num_group', models.IntegerField(help_text='Укажите номер группы', unique=True, verbose_name='номер группы')),
                ('priority', models.IntegerField(help_text='Укажите приоритет от 0 до 100', verbose_name='Приоритет')),
            ],
        ),
        migrations.CreateModel(
            name='LizaGroupPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Дайте короткое название группе', max_length=200, unique=True, verbose_name='Название группы')),
                ('num_group', models.IntegerField(help_text='Укажите номер группы', unique=True, verbose_name='номер группы')),
                ('priority', models.IntegerField(help_text='Укажите приоритет от 0 до 100', verbose_name='Приоритет')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Полное имя', max_length=200, unique=True, verbose_name='Имя')),
                ('sex', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('-', 'не определен')], default='-', max_length=1, verbose_name='Пол')),
                ('pub_date', models.DateTimeField(auto_now=True, help_text='Текущее время (авто)', verbose_name='Дата создания/изменения')),
                ('short_names', models.TextField(blank=True, help_text='Короткие имена через любой знак препинания или с новой строки', verbose_name='Короткие имена')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='LizaPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Введите текст фразы', max_length=200, unique=True, verbose_name='Фраза')),
                ('pub_date', models.DateTimeField(auto_now=True, help_text='Текущее время (авто)', verbose_name='Дата создания/изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LizaGroupPhrase', verbose_name='Принадлежность фразы к группе')),
            ],
        ),
        migrations.CreateModel(
            name='GermanPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Введите текст фразы', max_length=200, unique=True, verbose_name='Фраза')),
                ('pub_date', models.DateTimeField(auto_now=True, help_text='Текущее время (авто)', verbose_name='Дата создания/изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GermanGroupPhrase', verbose_name='Принадлежность фразы к группе')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Выберите файл', unique=True, upload_to='audio/wav', verbose_name='Звуковой файл')),
                ('pub_date', models.DateTimeField(auto_now=True, help_text='Текущее время (авто)', verbose_name='Дата создания/изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GermanGroupPhrase', verbose_name='Принадлежность фразы к группе')),
            ],
        ),
    ]
