# Generated by Django 3.0.5 on 2021-12-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ndzgroupphrase_ndzphrase_pzgroupphrase_pzphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndzphrase',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NdzGroupPhrase', verbose_name='Принадлежность фразы к группе'),
        ),
        migrations.AlterField(
            model_name='pzphrase',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PzGroupPhrase', verbose_name='Принадлежность фразы к группе'),
        ),
    ]
