# Generated by Django 3.0.5 on 2022-01-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomconnectCrmLid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lid', models.IntegerField(unique=True, verbose_name='ID лида')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Титл')),
                ('status_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Создано')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='Изменено')),
                ('source_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник')),
                ('assigned_by_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ASSIGNED_BY_ID')),
                ('crm_1493416385', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сумма тарифа')),
                ('crm_1499437861', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН/Организация')),
                ('crm_1580454770', models.CharField(blank=True, max_length=100, null=True, verbose_name='Звонок?')),
                ('crm_1534919765', models.CharField(blank=True, max_length=100, null=True, verbose_name='Группы источников')),
                ('crm_1571987728429', models.CharField(blank=True, max_length=100, null=True, verbose_name='Провайдеры ДК')),
                ('crm_1592566018', models.CharField(blank=True, max_length=100, null=True, verbose_name='ТИп лида')),
                ('crm_1493413514', models.CharField(blank=True, max_length=100, null=True, verbose_name='Провайдер')),
                ('crm_1492017494', models.CharField(blank=True, max_length=100, null=True, verbose_name='Область')),
                ('crm_1492017736', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('crm_1498756113', models.CharField(blank=True, max_length=100, null=True, verbose_name='Юр. лицо')),
                ('crm_1615982450', models.CharField(blank=True, max_length=100, null=True, verbose_name='utm_source')),
                ('crm_1615982567', models.CharField(blank=True, max_length=100, null=True, verbose_name='utm_medium')),
                ('crm_1615982644', models.CharField(blank=True, max_length=100, null=True, verbose_name='utm_campaign')),
                ('crm_1615982716', models.CharField(blank=True, max_length=100, null=True, verbose_name='utm_term')),
                ('crm_1615982795', models.CharField(blank=True, max_length=100, null=True, verbose_name='utm_content')),
                ('crm_1640267556', models.CharField(blank=True, max_length=100, null=True, verbose_name='utm_group')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('val_str', models.CharField(blank=True, max_length=100, null=True)),
                ('val_bool', models.BooleanField(blank=True, null=True)),
                ('val_int', models.IntegerField(blank=True, null=True)),
                ('val_datetime', models.DateTimeField(blank=True, null=True)),
                ('val_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
    ]
