# Generated by Django 3.0.5 on 2022-02-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DcCashSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_date', models.DateField(verbose_name='Период')),
                ('num_site', models.PositiveSmallIntegerField(verbose_name='Ном. Сайт')),
                ('num_source', models.PositiveSmallIntegerField(verbose_name='Ном. Источник')),
                ('row', models.PositiveSmallIntegerField(verbose_name='Строка')),
                ('val', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='DcCrmGlobVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('val_str', models.CharField(blank=True, default='', max_length=255)),
                ('val_bool', models.BooleanField(blank=True, default='False')),
                ('val_int', models.IntegerField(blank=True, null=True)),
                ('val_datetime', models.DateTimeField(blank=True, null=True)),
                ('val_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descriptions', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='DcCrmLid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lid', models.IntegerField(unique=True, verbose_name='ID лида')),
                ('title', models.CharField(blank=True, default='', max_length=512, verbose_name='Титл')),
                ('status_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Статус')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Создано')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='Изменено')),
                ('source_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Источник')),
                ('assigned_by_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Ответственный')),
                ('crm_1493416385', models.IntegerField(blank=True, default=0, verbose_name='Сумма тарифа')),
                ('crm_1499437861', models.CharField(blank=True, default='', max_length=255, verbose_name='ИНН/Организация')),
                ('crm_1580454770', models.BooleanField(blank=True, default=False, verbose_name='Звонок?')),
                ('crm_1534919765', models.CharField(blank=True, default='', max_length=255, verbose_name='Группы источников')),
                ('crm_1571987728429', models.CharField(blank=True, default='', max_length=255, verbose_name='Провайдеры ДК')),
                ('crm_1592566018', models.CharField(blank=True, default='', max_length=255, verbose_name='Тип лида')),
                ('crm_1493413514', models.CharField(blank=True, default='', max_length=255, verbose_name='Провайдер')),
                ('crm_1492017494', models.CharField(blank=True, default='', max_length=255, verbose_name='Область')),
                ('crm_1492017736', models.CharField(blank=True, default='', max_length=255, verbose_name='Город')),
                ('crm_1498756113', models.BooleanField(blank=True, default=False, verbose_name='Юр. лицо')),
                ('crm_1615982450', models.CharField(blank=True, default='', max_length=255, verbose_name='utm_source')),
                ('crm_1615982567', models.CharField(blank=True, default='', max_length=255, verbose_name='utm_medium')),
                ('crm_1615982644', models.CharField(blank=True, default='', max_length=255, verbose_name='utm_campaign')),
                ('crm_1615982716', models.CharField(blank=True, default='', max_length=255, verbose_name='utm_term')),
                ('crm_1615982795', models.CharField(blank=True, default='', max_length=255, verbose_name='utm_content')),
                ('crm_1640267556', models.CharField(blank=True, default=' ', max_length=255, verbose_name='utm_group')),
            ],
        ),
        migrations.CreateModel(
            name='DcSiteSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255, unique=True, verbose_name='Сайт')),
                ('provider', models.CharField(max_length=255, verbose_name='Провайдер')),
                ('num', models.PositiveSmallIntegerField(verbose_name='Номер п/п')),
            ],
        ),
        migrations.CreateModel(
            name='DcSourceSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, unique=True, verbose_name='Источник')),
                ('num', models.PositiveSmallIntegerField(verbose_name='Номер п/п')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='domconnect.DcSiteSEO', verbose_name='Сайт')),
            ],
        ),
    ]
