# Generated by Django 3.0.5 on 2022-01-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domconnect', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DcCrmTypeLid',
        ),
        migrations.AlterField(
            model_name='dccrmlid',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Источник'),
        ),
        migrations.DeleteModel(
            name='DcCrmTypeSource',
        ),
    ]
