# Generated by Django 3.0.5 on 2022-01-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domconnect', '0002_globalvariable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalvariable',
            name='val',
        ),
        migrations.AddField(
            model_name='globalvariable',
            name='val_bool',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='globalvariable',
            name='val_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalvariable',
            name='val_int',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='globalvariable',
            name='val_str',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
