# Generated by Django 3.0.5 on 2022-01-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domconnect', '0004_auto_20220128_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcSourceSiteSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, unique=True, verbose_name='Источник')),
                ('site', models.CharField(max_length=100, verbose_name='Сайт')),
                ('provider', models.CharField(max_length=100, verbose_name='Провайдер')),
            ],
        ),
    ]
