# Generated by Django 3.0.5 on 2022-01-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domconnect', '0005_auto_20220120_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domconnectcrmlid',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='domconnectcrmlid',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Изменено'),
        ),
    ]
