# Generated by Django 3.0.5 on 2022-02-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domconnect', '0005_auto_20220210_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='dccrmdeal',
            name='stage_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Стадия сделки'),
        ),
    ]
