# Generated by Django 3.0.5 on 2022-02-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domconnect', '0006_dccrmdeal_stage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dccrmdeal',
            name='stage_id',
        ),
    ]
