# Generated by Django 3.0.5 on 2022-01-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domconnect', '0008_auto_20220120_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domconnectcrmlid',
            name='assigned_by_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ASSIGNED_BY_ID'),
        ),
        migrations.AlterField(
            model_name='domconnectcrmlid',
            name='crm_1498756113',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Юр. лицо'),
        ),
        migrations.AlterField(
            model_name='domconnectcrmlid',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Источник'),
        ),
    ]
