# Generated by Django 3.2.3 on 2021-05-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_group_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'managed': True},
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_follow'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table='Follow',
        ),
    ]
