# Generated by Django 3.2.3 on 2021-05-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210528_0743'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='follow',
        ),
    ]
