# Generated by Django 3.2.3 on 2021-05-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_follow_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
    ]
