# Generated by Django 3.2.3 on 2021-05-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_follow_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
    ]
